
<h1>Patient</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="new" class="btn btn-primary">New Patient</a>
    <?=$message?>
</div>

<div class="table-responsive" style="margin: 50px 0 0px 0;">
    <form action="" method="get">
        <input type="text" name="con$condition"
        placeholder="Part of Name and Surname" value="<?=$condition?>" >
    </form>
    <?php include 'pagination.phtml' ?>
    <table class="table table-dark table-hover" style="margin: 20px 0 20px 0;">
        <thead>
            <tr>
                <th scope="col">Name and Surname</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col">Birth Date</th>
                <th scope="col">Oib</th>
                <th scope="col">Oxygen Concentrator</th>
                <th scope="col">Patient Comment</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data as $p): ?>
                <tr>
                    <td><?=$p->nameAndSurname?></td>
                    <td><?=$p->phone?></td>
                    <td><?=$p->address?></td>
                    <td><?=$p->birthDate?></td>
                    <td><?=$p->oib?></td>
                    <td><?=$p->serialNumber?></td>
                    <td>
                        <div class="form-floating">
                            <textarea class="form-control" id="floatingTextarea"><?=$p->patientComment?></textarea>
                        </div>
                    </td>
                    <td>
                    <?php if(App::admin()): //ako je auth admin?>
                        <a href="<?=APP::config('url')?>patient/update/<?=$p->id?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <?php if(0 === $p->delivered): ?>
                            <a 
                                onclick="return confirm('Deleting Patient <?=$p->nameAndSurname?> and all data about it(Collection and Deliveries) ? ')"
                                href="<?=APP::config('url')?>patient/delete/<?=$p->id?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i></a>
                        <?php else: ?>
                            <i title="OC is not collected from patient!" class="bi bi-trash3" style="color: grey;"></i>
                        <?php endif; ?>
                    <?php else: ?>
                        <i title="Only Admin can update Patient" class="bi bi-pencil" style="color: grey;"></i>
                        <i title="Only Admin can delete Patient" class="bi bi-trash3" style="color: grey;"></i>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php include 'pagination.phtml' ?>