<!DOCTYPE html>
    <html lang="en">
    <head>
        <?php include_once 'includes/head.phtml'; ?>
    </head>
    <body>
        <?php include_once 'includes/navbar.phtml'; ?>
        
        <div class="container" id="program">
            <?php echo $content; ?>
        </div>

        <?php include_once 'includes/footer.phtml'; ?>
        <?php include_once 'includes/script.phtml'; ?>
    </body>
</html>
