
<h1>Oxygen Concentrator</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="new" class="btn btn-primary">New Oxygen Concentrator</a>
    <?=$message?>
</div>

<div class="table-responsive" style="margin: 50px 0 0px 0;">
    <form action="" method="get" style="margin-bottom: 50px;">
        <input type="text" name="condition" style="width: 50%;" placeholder="Part of Serial Number" value="<?=$condition?>">
        <button type="submit">Search</button>
    </form>
    <?php include 'pagination.phtml' ?>
    <table class="table table-dark table-hover" style="margin: 20px 0 20px 0;">
        <thead>
            <tr>
                <th scope="col">Serial number</th>
                <th scope="col">Working hour's</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
                <th scope="col">Date of Buying</th>
                <th scope="col">Patient</th>
                <th scope="col">Comment</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data as $p): ?>
                <tr>
                    <td><?=$p->serialNumber?></td>
                    <td><?=$p->workingHour?></td>
                    <td><?=$p->manufacturer?></td>
                    <td><?=$p->model?></td>
                    <td><?=$p->buyingDate?></td>
                    <td><?=$p->nameAndSurname?></td>
                    <td>
                        <div class="form-floating">
                            <textarea class="form-control" id="floatingTextarea"><?=$p->oxygenConcentratorComment?></textarea>
                        </div>
                    </td>
                    
                    <td>
                    <?php if(App::admin()): //ako je auth admin?>
                        <a href="<?=APP::config('url')?>oxygenConcentrator/update/<?=$p->id?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <?php if(0 === $p->delivered): ?>
                            <a 
                                onclick="return confirm('Deleting Oxygen Concentrator <?=$p->serialNumber?> and all data about it(Collection and Deliveries) ? ')"
                                href="<?=APP::config('url')?>oxygenConcentrator/delete/<?=$p->id?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i></a>
                        <?php else: ?>
                            <i title="OC is not collected from patient!" class="bi bi-trash3" style="color: grey;"></i>
                        <?php endif; ?>
                    <?php else: ?>
                        <i title="Only Admin can update OC" class="bi bi-pencil" style="color: grey;"></i>
                        <i title="Only Admin can delete OC" class="bi bi-trash3" style="color: grey;"></i>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php include 'pagination.phtml' ?>