<div class="customModal" style="margin-top: 50px;">

    <div class="text-center" style="margin: 100px 0 0 0;">
        <h1>Update Oxygen Concentrator</h1>
    </div>

    <form class="row g-3" id="registrationForm" action="" method="post">
        <div class="col-md-6">
            <label for="serialNumber" class="form-label">OC Serial number</label>
            <input type="text" class="form-control" id="serialNumber" 
                name="serialNumber" value="<?=$e->serialNumber?>">
        </div>

        <div class="col-md-6">
            <label for="workingHour" class="form-label">OC Working hours</label>
            <input type="text" class="form-control" id="workingHour" 
                name="workingHour" value="<?=$e->workingHour?>">
        </div>
        <div class="col-md-6">
            <label for="manufacturer" class="form-label">Manufacturer</label>
            <input type="text" class="form-control" id="manufacturer" 
                name="manufacturer" value="<?=$e->manufacturer?>">
        </div>
        <div class="col-md-6">
            <label for="model" class="form-label">Model</label>
            <input type="text" class="form-control" id="model" 
                name="model" value="<?=$e->model?>">
        </div>
        <div class="col-md-6">
            <label for="oxygenConcentratorComment" class="form-label">Comment</label>
            <input type="text" class="form-control" id="oxygenConcentratorComment" 
                name="oxygenConcentratorComment" value="<?=$e->oxygenConcentratorComment?>">
        </div>
        <div class="col-md-6">
            <label for="buyingDate" class="form-label">Date of buying</label>
            <input type="text" class="form-control" id="buyingDate" 
                name="buyingDate" value="<?=$e->buyingDate?>">
        </div>
        <hr>
        <?=$message?>
        <div class="row" style="margin-top: 50px;">
            <div class="d-grid col">
                <button type="submit" class="btn btn-success" 
                value="update">Update</button>
            </div>
            <div class="d-grid col">
                <a href="<?=App::config('url')?>oxygenConcentrator/index"
                    class="btn btn-danger">Cancel</a> 
            </div>
        </div>
        
    </form>

</div>